version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.1.1 # node logcal ip Don't insert localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    image: minjuncho/netcc-be:2.2.3
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: 172.28.0.3
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: db
      JWT_SECRET: RKmMAaRBjVXdrpOaZgiwdUniYkJwpG
      JWT_EXPIRATION_TIME: 1000d
      KAFKA_BROKER: "10.32.103.147:9092"
      KAFKA_TOPIC: cctv
    networks:
      - net
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net

networks:
 net:
   driver: bridge

volumes:
  mysql-data:
    driver: local
